version: '3.8'

services:
  scrollsage:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped 